version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    environment:
      FLASK_APP: project/__init__.py
      SQL_HOST: db
      SQL_PORT: 3306
      APP_FOLDER: /home/app/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app -w 4
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'qwerty'
      MYSQL_ROOT_PASSWORD: 'root'
    command: --innodb-flush-log-at-trx-commit=0
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./scripts/table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data/mysql:/var/lib/mysql
