version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    environment:
      FLASK_APP=project/__init__.py
      SQL_HOST=db
      SQL_PORT=3306
      APP_FOLDER=/home/app/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app -w 4
    expose:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'qwerty'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
